btn_buynow_xpath = "//button[@class='_2KpZ6l _2U9uOA ihZ75k _3AWRsL']"
txt_userId_xpath = "//input[@class='_2IX_2- _17N0em']"
btn_continue_xpath = "//button[@class='_2KpZ6l _20xBvF _3AWRsL']"
txt_password_xpath = "//input[@class='_2IX_2- _3mctLh _17N0em']"
btn_login_xpath = "//button[@class='_2KpZ6l _20xBvF _3AWRsL']"
